version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/v2/"
  open-pull-requests-limit: 20
  schedule:
    interval: "weekly"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
