before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.BuildVersion={{.Version}}

    dir: cmd/stratus
    binary: stratus
dockers:
  - image_templates:
      - "ghcr.io/datadog/stratus-red-team:latest"
      - "ghcr.io/datadog/stratus-red-team:v{{ .Version }}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
