site_name: Stratus Red Team
site_url: https://stratus-red-team.cloud
repo_url: https://github.com/DataDog/stratus-red-team
repo_name: datadog/stratus-red-team
plugins:
  - search
  - awesome-pages
theme:
  name: material
  palette:
    primary: purple
  features:
  - navigation.expand
  - navigation.indexes
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky
use_directory_urls: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - tables
  - meta
  - abbr
  - def_list
  - attr_list
  - md_in_html


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - css/extra.css
  - css/w3.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/christophetd
copyright: Copyright 2021-Present Datadog, Inc.


nav:
  - <b>Stratus Red Team</b>:
      - index.md
      - Frequently Asked Questions: faq.md
      - Stratus Red Team vs. Other Tools: comparison.md
  - <b>User Guide</b>:
      - Getting Started: user-guide/getting-started.md
      - Sample Usage: user-guide/examples.md
      - Commands Reference:
          - list: user-guide/commands/list.md
          - status: user-guide/commands/status.md
          - show: user-guide/commands/show.md
          - warmup: user-guide/commands/warmup.md
          - detonate: user-guide/commands/detonate.md
          - revert: user-guide/commands/revert.md
          - cleanup: user-guide/commands/cleanup.md
      - Troubleshooting: user-guide/troubleshooting.md
      - Programmatic Usage: user-guide/programmatic-usage.md
  - <b>Attack Techniques Reference</b>:
      - All Attack Techniques: attack-techniques/list.md
      - Philosophy: attack-techniques/philosophy.md
      - Supported Platforms: attack-techniques/supported-platforms.md
      - Contributing: attack-techniques/contributing.md
      - ... | attack-techniques/*/*.md