name: "terraform lint"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: "Terraform lint"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # tag:v2.2.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag:v2.5.0
        with:
          fetch-depth: 1

      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # tag:v2
      
      - name: Lint Terraform
        run: terraform fmt -recursive -check
        working-directory: v2/internal/attacktechniques
        
